#!/usr/bin/env bash

# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37

BLACK='\033[0;30m'
RED='\033[0;31m' 
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m' 
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m' 
NC='\033[0m' # No Color

NONE=0
ERROR=1
SUCCESS=2
INFO=3
DEBUG=4

DRY=$1
LOG_LEVEL=${2^^}

# 0:OFF > *:ANY > 1:ERROR > 2:SUCCESS > 3:INFO > 4:DEBUG
log() {
    if [[ $LOG_LEVEL == "NONE" ]]; then
	return 0
    fi

    status=$1 
    stdoutput=""
    log=""
    
    case $status in
	"ERROR") 
	    stdout="${RED}[ERROR]:${NC} $2"
	    log="[ERROR]: $2"
	;;
	"SUCCESS") 
	    stdout="${GREEN}[SUCCESS]:${NC} $2"
	    log="[SUCCESS]: $2"
	;;
	"INFO") 
	    stdout="${ORANGE}[INFO]:${NC} $2"
	    log="[INFO]: $2"
	;;
	"DEBUG") 
	    stdout="${PURPLE}[DEBUG]:${NC} $2"
	    log="[DEBUG]: $2"
	;;
	*) 
	    stdout="$2"
	    log="$2"
	;;
    esac

    if [[ $DRY == true ]]; then
	stdout="${CYAN}[DRY_RUN]!${NC} => ${stdout}"
	log="[DRY_RUN]! => ${log}"
    fi
    
    print $stdout $log
}

print() {
    case $status in
	"DEBUG")
	    if [[ $LOG_LEVEL == "DEBUG" ]]; then
		echo -e "${stdout}"
		#echo "$( date '+%F_%H:%M:%S' ) ${log}" >> log.txt
	    fi
	;;
	"INFO")
	    if [[ $LOG_LEVEL -ge "INFO" ]]; then
		echo -e "${stdout}"
		#echo "$( date '+%F_%H:%M:%S' ) ${log}" >> log.txt
	    fi
	;;
	"SUCCESS")
	    if [[ $LOG_LEVEL -ge "SUCCESS" ]]; then
		echo -e "${stdout}"
		#echo "$( date '+%F_%H:%M:%S' ) ${log}" >> log.txt
	    fi
	;;
	"ERROR")
	    if [[ $LOG_LEVEL -ge "ERROR" ]]; then
		echo -e "${stdout}"
		#echo "$( date '+%F_%H:%M:%S' ) ${log}" >> log.txt
	    fi
	;;

	*) 
	    echo -e "${stdout}"
	    #echo "$( date '+%F_%H:%M:%S' ) ${log}" >> log.txt
	;;
    esac
}
